# Generated by Django 4.0.4 on 2022-05-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='descritption',
            new_name='description',
        ),
    ]
